### ISSUE TITLE
While using .Click I'm getting error

### ISSUE THREAD

**Issue by nareshdeee10** [er-ri/selenium-wrapper-vba#13]
![image](https://user-images.githubusercontent.com/50436121/204840782-b3e4fe94-7ea9-49a7-b083-600fc340328a.png)
I'm getting the above error while trying to automate google page search particularly while clicking the google search button.

Below is my code:
Sub Example3()
    Set driver = New WebDriver

    driver.Chrome "DriverPath\chromedriver.exe"
    driver.OpenBrowser
    driver.NavigateTo "https://www.google.com/"
    driver.FindElement(By.name, "q").SendKeys "Cricket Live Score"
    driver.FindElement(By.name, "btnK").Click  'Here I'm Getting the error while clicking
    Debug.Print driver.FindElement(By.name, "btnK").GetAttribute("value") 'Here I'm not getting an error but I can able to the value

    driver.CloseBrowser
    driver.Quit
    Set driver = Nothing
End Sub

Question - can you please assist me with how to use click and fix the issue.

**Comment by er-ri** [comment]
The `Google Search` button was not clickable because the element was hidden by the 'autocomplete predictions'. Turning off the 'autocomplete predictions' function or locating the `Google Search` button on the `autocomplete predictions` to perform the clicking may solve the problem. Remember, make sure the element is visible during the operation. 
Anyway, using an `Enter` key to send the query is preferred, but the function has not been implemented.

**Comment by nareshdeee10** [comment]
Thank you for the response, 
1) here i have clarification are you referring to turn off the 'autocomplete predictions' this is in browser or on the code?
2) I'm trying to use click method when the button is visible, adding to that driver.FindElement(By.name, "btnK").GetAttribute("value") when i use this i can able to get the value of the element without any error.

**Comment by er-ri** [comment]
1. Google 'autocomplete predictions':
https://support.google.com/websearch/answer/106230

2. The button is covered by the 'autocomplete predictions', not visible&clickable.
![image](https://user-images.githubusercontent.com/50995184/205266899-a076c842-ba70-46be-83fe-d382dd021191.png)
